resources:
  - kind: repository
    selector:
      query: 'true'
      includeLanguages: 'true'
    port:
      entity:
        mappings:
          identifier: .full_name | gsub(" "; "")
          title: .name
          blueprint: '"githubRepository"'
          properties:
            url: .html_url
            readme: file://README.md
            language: .__languages | to_entries | max_by(.value) | .key
  - kind: user
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .login
          title: .name
          blueprint: '"githubMember"'
          properties:
            url: .html_url
            email: .email
  - kind: team
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .slug
          title: .name
          blueprint: '"githubTeam"'
          properties:
            url: .html_url
            description: .description
          relations:
            githubMembers: .__members | map(.login)
  - kind: pull-request
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"githubPullRequest"'
          properties:
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            link: .html_url
            reviewers: .requested_reviewers | map(.login)
          relations:
            repository: .repository.full_name
  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"githubIssue"'
          properties:
            createdAt: .created_at
            updatedAt: .updated_at
            closedAt: .closed_at
            link: .html_url
            author: .user.login
            milestone: .milestone.titles
          relations:
            repository: .repository.full_name
  - kind: workflow
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name // .workflow_name // "Workflow Run"
          blueprint: '"githubWorkflow"'
          properties:
            workflowName: .workflow.name // .workflow_name
            runNumber: .run_number
            event: .event
            branch: .head_branch
            actor: .actor.login
            createdAt: .created_at
            updatedAt: .updated_at
            runStartedAt: .run_started_at
            link: .html_url
          relations:
            repository: .repository.full_name
